apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastcrowdvision
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aayrapet/FastCrowdVision.git
    targetRevision: feat/argocd-migration
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: user-<IDEP>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
